### ISSUE TITLE
Draw over permission doesn't allow installations

### ISSUE THREAD

**Issue by ghost** [gabm/TapAndTurn#10]
Great app man, just what I always needed/wanted.

I have seen that once the Draw over apps permission is activated, and I either want to install or update a new apk file or from F-droid, I'm unable to tap on the install button. If I deactivate the permission, I can tap the option without any problem.

**Comment by gabm** [comment]
thanks for the kind words...

that's a known issue and related to #3. Please update to v2.1.1 which is the latest version on F-Droid. Now when you have running Tap n Turn in a version below 2.1.1 you'll not be able to install the update.

In this case just reboot your phone and before starting the Tap n Turn you go to F-Droid and update it...

**Comment by licaon-kter** [comment]
There is no need to reboot, a simple ForceClose in Android>Settings>Apps does the trick.
