### ISSUE TITLE
Swipe ‘down’ to set orientation and zero tilt

### ISSUE THREAD

**Issue by JRHaigh** [gabm/TapAndTurn#11]
Thank you so much for making this libre application! For years I've had a similar idea, which, like Tap 'n' Turn, would provide a brief translucent overlay to give the user better control of rotation while still making use of the accelerometer.
&nbsp;&nbsp;&nbsp;&nbsp;The idea was that when the device tilts beyond a threshold (e.g. 60°) relative to a tilt offset, an overlay appears which allows the user to swipe towards the desired bottom edge of the screen to indicate the desired orientation, upon which 2 things happen: –
* the screen orientation is set accordingly, which if different than before then rotation occurs; and
* the tilt is zeroed, i.e. the tilt offset for the calibrated tilt parameter is set to the current device tilt derived from the accelerometer.

Note that this allows the tilt to be zeroed without rotation, simply to dismiss the overlay after the user changes their physical orientation (i.e. standing/sitting, lying on left, lying on right, hanging upsidedown, or anywhere inbetween these).
&nbsp;&nbsp;&nbsp;&nbsp;The downwards swipe could begin from a translucent button that appears in the middle but this would be too intrusive. I think that it would be much better to have 2 buttons placed in opposite corners, as this would be much less annoying yet still allow all 4 swipe directions.
&nbsp;&nbsp;&nbsp;&nbsp;Tap 'n' Turn already has a button in 1 corner, so just 1 more button is needed in the opposite corner to enable the other 2 swipe directions. Other than that the existing functionality can be identical – a single tap merely rotates in the manner that it currently does and resets the tilt offset to zero.

**Comment by JRHaigh** [comment]
The second button should be optional, but the default should still allow the 2 swipe directions that it can. With a subtle change to the current default behaviour, namely the position of the single button to always be in the corner that is both at the top of the current logical screen and at the top as indicated by the accelerometer, the 2 swipe directions available by default can correspond to whether the user has changed physical orientation or wants to change screen orientation between portrait and landscape, which are almost always independent events. Respectively, the single button's 2 swipe directions can be seen as ‘dismiss and zero tilt’ and ‘rotate and zero tilt’. (Tapping is ‘rotate and reset tilt offset’.)

**Comment by gabm** [comment]
@JRHaigh Thank you so much for your ideas and input. Your ideas sound very sophisticated and with a lot thought beforehand... 

I think the problem you are tackling can be described as: *Holding the device in a 45° angle causes the turning icon to appear and disappear rapidly, which bothers the user*

Do you agree with that?

If so, then the suggested solution will solve this issue. But I have the feeling that it could confuse the user. Additional input (swipe in a certain direction) would require more learning/understanding than *I tap and it turns..*.  Maybe it would be necessary to display the current setting to the user (via a line on the display) to make it more visual...

Anyway, this is an Open Source project and I'd love to see it as a hub for experimentation and ideas. So maybe we can implemented in a way, that preserves the original behavior and offer it as an advanced mode. If you feel like, you are more than welcome to contribute :+1:
