### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by JRHaigh** [gabm/TapAndTurn#13]
I imagine that [Chibe](https://f-droid.org/app/com.jmstudios.chibe) is among the simplest examples that use the run-at-startup permission, so it may be worth studying that to learn how to reliably be running whenever the ‘Tap 'n' Turn Service Running’ switch is enabled.

**Comment by gabm** [comment]
this has been on my list, I'll definitely look into this...

**Comment by licaon-kter** [comment]
This part https://github.com/raatmarien/chibe/blob/master/src/main/java/com/jmstudios/chibe/state/BootReceiver.java

**Comment by gabm** [comment]
I released a beta version that includes this feature on f-droid (requires manual update once its relased)... 

https://gitlab.com/fdroid/fdroiddata/merge_requests/1889/

Please check with this version and report back..

**Comment by gabm** [comment]
I'll release a new version soon which contains this functionality as implemented in the last beta
