### ISSUE TITLE
Not work on Xiaomi Redmi Note 3

### ISSUE THREAD

**Issue by einhander** [gabm/TapAndTurn#15]
Hi, I installed your app from f-droid  repo.
Icon not displayed and rotation work as usual.
Service enabled and permission granted in app.

**Comment by gabm** [comment]
did u disable auto rotation of android? can you confirm that the service is running (persistent notification)

**Comment by einhander** [comment]
I tried it with auto rotation and disabled auto rotation. Persistent
notification works.

17 дек. 2016 г. 13:15 пользователь "gabm" <notifications@github.com>
написал:

did u disable auto rotation of android? can you confirm that the service is
running (persistent notification)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gabm/TapAndTurn/issues/15#issuecomment-267754886>, or mute
the thread

**Comment by gabm** [comment]
hmmm to be honest, i have no idea what's going on .. you may want to try to debug it yourself?!

**Comment by einhander** [comment]
What should I do to debug?

17 дек. 2016 г. 18:11 пользователь "gabm" <notifications@github.com>
написал:

**Comment by gabm** [comment]
what knowledge of android development do u have? have you used android-studio? git? ... do you know how to program?

the overall procedure would be: clone the source code, build it in your android studio, start with debugger, put breakpoints and see what happens/not happens
