### ISSUE TITLE
App rotation confusion

### ISSUE THREAD

**Issue by licaon-kter** [gabm/TapAndTurn#17]
This is the reason #16 exists.

Xperia 5.1.1, app version 2.1.1 (from F-Droid)

Steps:
* rotation lock on portrait
* open [Document Viewer](https://github.com/SufficientlySecure/document-viewer) (or Total Commander or I guess any app)
* app is portrait -> OK
* rotate device to landscape -> app stays portrait (as expected) -> tapnturn icon appears in upper right side -> OK (if you don't touch the icon everything is ok)
* rotate device to portrait -> no tapnturn icon appears (as expected) -> OK 
* rotate device to landscape -> app stays portrait (as expected) -> tapnturn icon appears in upper right side -> TOUCH THE ICON -> app rotates (as expected) -> OK
* rotate device to portrait -> tapnturn icon appears in upper right side -> DO NOT TOUCH IT -> app stays in landscape (as expected) -> OK
* rotate device to landscape -> NO tapnturn icon appears -> app is rotated to portrait ( NOT as expected) -> NOT OK
* rotate device to portrait -> tapnturn icon appears in upper right side (as expected)  -> app is rotated to landscape ( NOT as expected) -> after the icon disappears app is rotated to portrait ( NOT as expected)
* rotate device to landscape -> NO tapnturn icon appears -> app stays in portrait 
* rotate device to portrait -> tapnturn icon appears in upper right side (as expected)  -> app is rotated to landscape ( NOT as expected) -> after the icon disappears app is rotated to portrait ( NOT as expected)
* need to kill the app since it misbehaves

Hope some one can repro this based on my steps, this would be painful to film

**Comment by gabm** [comment]
Thanks - good findings!
I can 100% reproduce it on my phone - I'm sure its a problem in the overlay - I'll have a look into this tonight...

**Comment by gabm** [comment]
Ok, I'll do it like this:
- We need to have the dummy overlay enabled all the time to "force" a certain orientation
  - removing the dummy overlay at some occasions as introduced by the fix for "not being able to press restricted buttons" has introduced your bug
- Adding the dummy overlay all the time will consequently reintroduce #3 
- My Idea to solve this would be: "Only add the dummy overlay, whenever we need to *force* a different orientation than the default specified one"
  - that would mean: you can press restricted buttons (like the install button) in the default, fixed orientation (portrait on most phones)
- additionally/alternatively we could add a pause button to the persistent notification

What do you think?

P.S.: I added a https://riot.im channel for discussion and support some days go: #TapAndTurn:matrix.org   -> also specified in the readme :)

**Comment by licaon-kter** [comment]
No idea if the overlay works, but I'll test ( https://github.com/gabm/TapAndTurn/commit/ce4d8c5c155d988bb5f9d410fd37f77f13c27cb6 has the fix, right? )
Regarding the button, I don't really care as I hide the notification.

Regarding #3, the initial idea "remove for secure apps" sounded nice, whould it not be better to implement it exactly as RedMoon does with `isAppSecured()` ?

/PS: I'd rather keep the discussions here where can be found easily.

**Comment by gabm** [comment]
I'll release a new version soon that fixes your issue here. The overlay that enforces rotation will only be added, when it's not default orientation .. so the orientation setting works and the restricted android system buttons only work in the default orientation...

**Comment by licaon-kter** [comment]
This happens still, but only when rotating 90 degrees clockwise (left side becomes top side)

**Comment by licaon-kter** [comment]
Any new ideas for this one? I would like to use this app, but not when it goes crazy like this. :-/

**Comment by gabm** [comment]
i think that things should work much better with the new update..  i really somehow messed up the state handing and things got a not out of hand... please check after the update and let me know! now there is no state and no strange magic anymore...

**Comment by gabm** [comment]
... further you should enable the automatic rotation

**Comment by licaon-kter** [comment]
What do you automatic? The whole point was that I don't want to use that.

I'll test when the update comes.

**Comment by gabm** [comment]
no, dont get me wrong.. its a bit confusing...

In General: No matter whether auto rotation is enabled or disabled in the system, if TnT is running on top of that it enforces a certain orientation by specifically requesting that. However, it seems there are a lot of inconsistencies on how vendors ship their software...

- On my Samsung Tablet: if Auto Rotation is enabled and TnT is running, then everything works as expected. If Auto Rotation is disabled and TnT is running, then "Reveres Landscape" is set and communicated by the API as expected, except that the actually applied orientation of the screen is "Landscape".
- On my OnePlus phone: if Auto Rotation is enabled and TnT is running, then everything works as expected. If Auto Rotation is disabled, then Reverse Portrait doesn't work.

Of course, if TnT is disabled, you get what you have configured in android... 

So verdict is: TnT overrides the setting of Android by requesting something different. Think of a game running that wants to be played in Landscape mode on a Phone... It will always turn the screen, even if auto-rotation is disabled. However, it seems to work better, when TnT operates when the android auto rotation is *enabled*

**Comment by licaon-kter** [comment]
Ok, counterintuitive but I'll test.

**Comment by gabm** [comment]
please check back, v2.3.0 got released today!

**Comment by licaon-kter** [comment]
Looks ok in 2.3.0. thanks
