### ISSUE TITLE
Can change the position of the icon (other corner)?

### ISSUE THREAD

**Issue by skorotkiewicz** [gabm/TapAndTurn#19]
Can change the position of the icon (other corner)?

**Comment by gabm** [comment]
currently not... it's designed for right-handed people currently (the icon appears in the top right corner)

What would you have in mind? a simple left-handed mode would be very very easy but everything more sophisticated would require more work...

**Comment by skorotkiewicz** [comment]
hmm, simple left-handed mode

**Comment by gabm** [comment]
I'll release a new version soon which contains a simple switch to ass left handed mode
