### ISSUE TITLE
Screen goes black

### ISSUE THREAD

**Issue by dalb8** [gabm/TapAndTurn#22]
On LG G4 running Android 6 when I press the power button to wake the phone up the lock screen sometimes doesn't appear: only a black coloured screen. I can fix it by launching an app with a volume button combo and rotating the screen with Tap & Turn; then the lock screen appears.

**Comment by gabm** [comment]
Uuh that sounds strange. could you try to collect some logs using aLogcat (in the playstore)?

**Comment by dalb8** [comment]
I don't have root. 

The lock screen itself must be rotating as there is a 'pull to show the time' function from screen off and that is rotated.

**Comment by gabm** [comment]
This should be fixed in v2.3.0 which will be released to F-Droid in some days...
