### ISSUE TITLE
Two feature requests

### ISSUE THREAD

**Issue by Avasz** [gabm/TapAndTurn#23]
First of all thank you for such great app! I discovered this today, and very happy with it. I would like to request two things:
1. Option to hide the notification on notification bar.

2. If possible threshold or wait a few seconds before displaying the icon. Because when moving it shows the icon a lot of time for minimum tilt required to trigger the action.

Device: Oneplus 3
Rom: Resurrection Remix, Marshmallow.

Thank you very much.

**Comment by licaon-kter** [comment]
Long press on notification, info, block!?

It's part of Android since 5.

**Comment by gabm** [comment]
1) can be solved by hiding the notification. technically it's necessary that the notification is displayed, but the user can hide it...

2) that would be very useful. When I have time Ill have a look into this. shouldn't be too hard though, so if you want you're invited to have a look into this and provide a PR

**Comment by gabm** [comment]
I implemented a little hysteresis, which should prevent from displaying the icon too often. This should be fixed in v2.3.0 which will be released to F-Droid in some days...
