### ISSUE TITLE
Allow reverse orientations

### ISSUE THREAD

**Issue by Basti1512** [gabm/TapAndTurn#24]
Sometimes I'd like to use my device upside-down. It would be great if you enable this orientation in an upcoming release! :-)
BR Basti

**Comment by gabm** [comment]
there is an option to switch this on in the settings menu of the app.

However: on most phone devices this orientation is not enabled and will most likely not work. On tablets however you have a chance to get things working the way you want.

**Comment by gabm** [comment]
there is an option to switch this on in the settings menu of the app.

However: on most phone devices this orientation is not enabled and will most likely not work. On tablets however you have a chance to get things working the way you want.

**Comment by Basti1512** [comment]
Basically the upside-down ortientation is working on my device (rooted with Xposed/GravityBox). But after turning off the automatic option in Android your app doesn't turn the screen upside-down anymore.

**Comment by mtbu** [comment]
On LineageOS 14.1 upside-down mode in Tap'n'turn seems to work if autorotate is enabled from the quick settings toggle, although if rotation is locked from the quick settings then the screen can go into any mode other than upside down. Maybe it's some limitation with Android like you suggest?
