### ISSUE TITLE
Unable to scroll to see other settings.

### ISSUE THREAD

**Issue by Jayman2000** [gabm/TapAndTurn#26]
I have a Droid Turbo 2 running Android 7.0.

Some settings appear to be cut off, and I can't scroll down to see them. Screenshot: https://goo.gl/photos/41Pq9ahdaSXigsCUA

**Comment by licaon-kter** [comment]
Use Android settings and make the UI smaller (not the font, the other thing that they introduced in Android 7), set up stuff, then bright it back to your preferred size.

**Comment by yubimoto** [comment]
I have the same issue using a Moto G1 + CM13.
Reducing the fontsize also works, since in CM13 doesn't have Android 7 features.

**Comment by gabm** [comment]
This should be fixed in v2.3.0 which will be released to F-Droid in some days...

**Comment by gabm** [comment]
please check back, v2.3.0 got released today!
