### ISSUE TITLE
Polls sensors even when screen is off

### ISSUE THREAD

**Issue by haarp** [gabm/TapAndTurn#28]
Hey!

When the Tap and Turn service is enabled while the screen is off, I see lots of sensor activitiy in Logcat, such as:

    sensors_hal_Ctx: poll:polldata:24, sensor:0, type:1, x:-0.189835 y:-0.219513 z:9.607086

It doesn't happen when the service is disabled.

This is a source of battery drain that could be avoided, since there is no point in polling while the screen is off. :)

Thanks!

**Comment by licaon-kter** [comment]
Do you have proof for such a drain?

**Comment by haarp** [comment]
No, I have no proof that the drain is significant. It's probably tiny.

But it stands to reason that using sensors and CPU cycles is more costly on the battery than not using them ;) Why do it at all when it's not necessary?

**Comment by licaon-kter** [comment]
What sensor is that exactly?

Can you get BetterBatteryStats and see what that says about consumption and usage?

**Comment by gabm** [comment]
the sensor access needs to be there, because android is not sending any event, when the rotation is locked... so without active sensor access by the app we won't notice when the user physically rotates the device. However: this continuous access did not result in measurable battery consumption for me.

I agree, that it could probably be avoided while the screen is off...

**Comment by haarp** [comment]
> What sensor is that exactly?

It's the accelerometer:

    05-14 14:48:45.649   831  1043 V sensors_hal_Accel: processReportInd: X: 8.283569 Y: -3.775085 Z: -3.051102 
    05-14 14:48:45.649   831  1043 V sensors_hal_Accel: processReportInd: X: 8.266220 Y: -3.784500 Z: -3.050400 
    05-14 14:48:45.649   831  1043 V sensors_hal_Accel: processReportInd: X: 8.225555 Y: -3.772217 Z: -3.032333 
    05-14 14:48:45.649   831  1043 V sensors_hal_Accel: processReportInd: X: 8.266037 Y: -3.791397 Z: -3.006226
    ....

and if the phone is moved at the same time (e.g. it is in the pocket), lots of activity is triggered, which is bound to keep the CPU from transitioning into deep sleep:

    05-14 14:50:24.215  3799  3799 I Orientation: 1
    05-14 14:50:24.215  3799  3799 I Orientation: 8
    05-14 14:50:24.216  3799  3799 I getBoolean: LEFT_HANDED_MODE
    05-14 14:50:24.216  3799  3799 I OrientationChange:: left handed, old: 1 new: 8
    05-14 14:50:24.242  3799  3799 I Orientation: 0
    05-14 14:50:24.252  3799  3799 I getBoolean: LEFT_HANDED_MODE
    05-14 14:50:24.253  3799  3799 I OrientationChange:: left handed, old: 1 new: 0
    05-14 14:50:24.275  3799  3799 I Orientation: 8
    05-14 14:50:24.276  3799  3799 I getBoolean: LEFT_HANDED_MODE
    05-14 14:50:24.276  3799  3799 I OrientationChange:: left handed, old: 1 new: 8
    05-14 14:50:24.283  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    05-14 14:50:24.283  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    05-14 14:50:24.283  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    05-14 14:50:24.284  3799  3799 I Orientation: 0
    05-14 14:50:24.284  3799  3799 I getBoolean: LEFT_HANDED_MODE
    05-14 14:50:24.284  3799  3799 I OrientationChange:: left handed, old: 1 new: 0
    05-14 14:50:24.298  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    05-14 14:50:24.298  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    05-14 14:50:24.298  3799  3799 I getBoolean: USE_REVERSE_PORTRAIT
    ....

> Can you get BetterBatteryStats and see what that says about consumption and usage?

On an idling phone:

Tap and Turn enabled: DeepSleep=72%, Awake(screen off)=28%

Tap and Turn disabled: DeepSleep=81%, Awake(Screen off)=19%

So it does make a considerable difference.

**Comment by gabm** [comment]
very nice work.. obvious indeed...

probably we should pause the orientation monitoring in the Service that looks for that.
https://github.com/gabm/TapAndTurn/blob/master/app/src/main/java/com/gabm/tapandturn/services/ServiceRotationControlService.java

So we should receive the `Intent.ACTION_SCREEN_OFF` Broadcast there and pause the OrientationSensor with `disable()`...

**Comment by gabm** [comment]
I plan to release a new version soon where this should be fixed.. please be patient for some days

**Comment by gabm** [comment]
This should be fixed in v2.3.0 which will be released to F-Droid in some days...

**Comment by gabm** [comment]
please check back, v2.3.0 got released today!

**Comment by haarp** [comment]
This works. Thanks! :+1:
