### ISSUE TITLE
Switch back to default Rotation/Orientation when locking the Screen

### ISSUE THREAD

**Issue by just-Nob** [gabm/TapAndTurn#30]
I've some issues if my LG G3 phone (rooted device with running the latest Marshmallow stock ROM on it) locks the screen with the rotation being in landscape mode (driven by T'n'T), for example when pausing to watch landscape oriented photos or to play a game in landscape mode.

When this happens, usually I have a problem to unlock the phone; most times, the only chance that I have is to remove the battery for forcing a very hard reboot.

It would be great to have a T'n'T-option like "always force default (or portrait/landscape, depending on the device's default orientation) orientation after locking the screen".

**Comment by gabm** [comment]
Thanks for your bug report, its very unfortunate that it crashes your phone in that manner :/

Can u try to find a pattern? Does it happen all the time? If not, can u try to distinguish the following three patterns:

1. Lock the device in Portrait mode, don't rotate it, unlock it in the same orientation
2. Lock the device in Portrait mode, rotate it 360°, step by step, unlock it in Portrait mode
3. Lock the device in Portrait mode, rotate it 90° and unlock it in Landscape mode...

It could actually be, that I'm re-enabling the orientation sensor too early ...

**Comment by gayprogrammer** [comment]
I don't have this issue, but I would actually like this as a feature. There is no icon to change orientation at the lockscreen. I am fine with not being able to change orientation from the lock screen if there were an option to reset after locking. 

My use case is that I forget that it was previously landscape, I expect it to be "reset" to portrait by default. I would like that option.

**Comment by licaon-kter** [comment]
Been wishing for this too!

**Comment by gabm** [comment]
You're right, that makes a lot of sense... I implemented this but its actually tricky to get this "default orientation" ... on my phone it seems to work but i don't know on tablets and so on..

Guess I'll release a beta to let you guys test it...

**Comment by gabm** [comment]
... not sure of this will help to solve the OPs problem though

**Comment by gayprogrammer** [comment]
@gabm If the "reset when locked" setting is optional, and the default orientation can be selected in settings, then it should be okay for tablet users, and it sounds like it does fix OPs problem.

**Comment by just-Nob** [comment]
Sorry for the delayed reply.
I'm a little in a hurry, but I'll check this out this weekend.

Anyway, it isn't a real crash, but more a kind off "UI deadlock".
The phone still works, but isn't able to unlock...

More details coming soon!

**Comment by just-Nob** [comment]
Ok, let's describe the problem a little more in detail. ;) 
Checked it out latest time with T'n'T V. 2.5.0.

I've checked out all three described cases - these are all ok and make no trouble.
In general, especially when screen goes off being in portrait mode (which is my phone's standard orientation, like with almost every other phone), there's no problem when screen is switched on again and lock screen appears.

The problem occurs when doing the following:
1. Turn the phone's orientation from portrait to landscape by using T'n'T (e.g. for watching landscape photos).
2. Lock the screen by a short push on the power button. Don't leave the app before by pushing/tapping "Home" (this may not be necessary, I'm not sure about it, but it's my standard case).
3. Wait a few seconds.
4. Try to turn on the phone/screen by pressing the power button again. Mostly, nothing happens and the lock screen doesn't come up, the screen leaves black. Sometimes, after some tries, the lock screen comes up in landscape, but unfortunately I wasn't able to reproduce it in a reliable manner.

**Comment by gabm** [comment]
ok.. i implemented a feature that disables TnT on lock and re-enables it after the device has been unlocked. Apart from the screen off event not firing reliably on my phone (sometimes it's late) it looks good... think that should solve your problem. I'll release it soon..

**Comment by just-Nob** [comment]
Thx!
I'll give you a feedback asap.

**Comment by just-Nob** [comment]
Sorry, I was absent for some month due to some serious, heavy health issues.
Anyway, as you may have presumed, this feature works really well, both on my old LG G3 as well as on my brand-new BQ Aquaris X Pro.
I guess it's time to close this issue. 😀

**Comment by licaon-kter** [comment]
So... close it yourself ;)
