### ISSUE TITLE
Add T'n'T's current Version Number somewhere on the App's Screen

### ISSUE THREAD

**Issue by just-Nob** [gabm/TapAndTurn#34]
Would be glad to have the current installed app's version number somewhere on T'n'T's screen... - it's not impossible to get it from system, but would be a little easier that way. ;)

**Comment by gabm** [comment]
yeah sounds reasonable.. maybe it could also contain a link to the website and the license/contributors..

Do you want to give it a shot?

**Comment by just-Nob** [comment]
I'd do so, if I was skilled enough.
Unfortunately, I haven't java / Android app programming skills yet. That's something being noticed at my private todo list, but haven't had the time for learning up to now... :( 
(Anyway, I have experiences in some other programming languages, but java's new too me.)

At the moment, I'm being here for getting familiar with Github as well as giving some feedback & bug reporting; maybe some German translations as well... ;)

**Comment by gabm** [comment]
ok.. no worries.. let's see when i find time...

anything apart from programming will be happily accepted as well.... translations, artwork etc

**Comment by gabm** [comment]
this has been fixed in v2.7.0
