### ISSUE TITLE
strange problems with camera apps

### ISSUE THREAD

**Issue by ghost** [gabm/TapAndTurn#35]
OpenCamera "rotates itself" when T&T is active. That is, if screen is upright all the times, OpenCamera will have its user interface rotated by 90 degrees if T&T is active. 
It appears this is because for some reason OpenCamera rotates itself on startup to get its layout and T&T prevents this from working. The app is still usable, just looks strange.

 CamTimer (also in f-droid repo) has the same problem, and looks very ugly as result.

**Comment by gabm** [comment]
Thanks for your report.. unfortunately some apps are not designed to work with another app determining the rotation.. this can only be solved by #8 or something similar...  I'll close it here, we should discuss there...
