### ISSUE TITLE
[Feature request] Please add an option to turn off audio notification

### ISSUE THREAD

**Issue by samandiriel** [gabm/TapAndTurn#46]
It can be very annoying over my headset when I am moving around a lot and my highly sensitive phone  is constantly signalling an orientation switch.

**Comment by licaon-kter** [comment]
That's not an app feature though.

On my ROMs I don't have this. Can you try to control it in your Android settings?

What device? What Android version?

**Comment by samandiriel** [comment]
Oh - I had no idea it was a systems issue.  I'm running rooted stock Oxygen OS on the OnePlus 5, with 7.1.1.  It's surprising then, as it has a hardware slider that's supposed to mute all sound but doesn't for the app notification.  The other audio settings don't seem to apply - things like screen locking sound, screenshot sound, etc.  Sorry to have bothered you with what is a phone issue!

**Comment by gabm** [comment]
Thanks for your request. I'm afraid TnT (and probably any other app) can't do anything for you here...  Seems like a strange behavior of your ROM..
