### ISSUE TITLE
Android P new feature

### ISSUE THREAD

**Issue by licaon-kter** [gabm/TapAndTurn#47]
> If the phone is locked to portrait and held in landscape, a new rotate icon will show up in the navigation bar.

![pic](https://i.imgur.com/sTjKFKu.jpg)

> Rotation gets a nice new improvement, too. If the phone is locked to portrait mode and held in landscape, a new rotation icon will pop up in the navigation bar. This won't re-enable auto rotate, it will instead lock the phone to the current orientation.

Source: https://arstechnica.com/gadgets/2018/03/hands-on-with-android-p-is-this-the-beginning-of-a-new-design-language/

**Comment by S0und** [comment]
Could you offer a similar implementation option? So the Rotate button **stays** at the same corner of the screen. Right now it's like a 'reflex game' you have 2 seconds to click the button that depending on the orientation pops up in a different corner.

**Comment by licaon-kter** [comment]
@S0und In navbar would be nice but tricky

> So the Rotate button stays at the same corner of the screen.

It stays in the same corner... set it up in settings. _(it's the same place in relation to my hands, it's predictable)._

**Comment by S0und** [comment]
Which settings is that? 

https://www.youtube.com/watch?v=yOkXvm6-6AU

My expectation:

To avoid confusion: https://i.imgur.com/6vPYBnO.png

If the button stays in the same corner, regardless the orientation it should say in corner 4. But when i go from landscape to portrait, it's in corner 2.

**Comment by licaon-kter** [comment]
That would make it out of reach 50% of time, why would you want that?

**Comment by S0und** [comment]
I'm pretty sure we miss understand each other. 

This is how this feature works in Android P. Using my analogy, the button stays in corner 3, regardless the orientation. I suggested the same thing, but with corner 4 (w/e). How is this "out of reach 50% of the time" ? I just don't get it. 

https://youtu.be/pKPmwjVJhq8?t=321

this is how your app functions on my phone: https://www.youtube.com/watch?v=yOkXvm6-6AU

The button jumps around, it's either in corner 4 or corner 2

**Comment by licaon-kter** [comment]
_not my app_

Again, It does not jump around it stays in the same corner **relative to the way the device is used**.

I would find it annoying to be fixed there (either 3 or 4), it's out of reach for me when rotating from portrait to landscape, clockwise.

**Comment by zilexa** [comment]
I received the OTA of Android 9 on my Pixel 1: the feature you mentioned is not available. 

Thankfully I discovered this app and OMG!! It is the best ever. Android 9 stupidified the Android experience for me. If I could roll back to 8.1 I would do so immediately. Thankfully TapAndTurn makes it a bit better. 

I also highly agree the way TapAndTurn works placing the icon in the same corner relative to screen orientation is simply well thought through design and makes more sense so please don't change it, the way it is now works best.

**Comment by gabm** [comment]
I think the current way of working is quite intuitive.. once we solved the stability issues we can extend the features.. I am very open to PRs..
