### ISSUE TITLE
Can nit allow adb to connect to the device while overlay is ebalbed for tap'n'turn

### ISSUE THREAD

**Issue by githtz** [gabm/TapAndTurn#49]
When tap'n'turn overlay permissions are enabled it is not possible to press the ok-button on the dialog to allow adb connections since lineageos detects there is an app obscuring the dialog.
This works again once the overlay permission was revoked from tap'n'turn. For other apps using the overlay permission it does work even if the permission is granted though. Is there a fix available for that problem?

Device: LG G3 D855
LineageOS: 14.1 / android 7.1

**Comment by licaon-kter** [comment]
Not for all, eg. NavigationGestures behaves the same on Oreo for me, but not Tap'n'Turn.

**Comment by githtz** [comment]
So the solution is just the same as mentioned in #21, to disable the service temporarily? I'm okay with that, just got irritated by the popup...

//edit

My bad, should have looked at #27 and #38 before opening this issue. Gonna close this now.
