### ISSUE TITLE
"There was a problem while parsing the package"

### ISSUE THREAD

**Issue by netmackan** [gabm/TapAndTurn#5]
Error message when trying to install from F-droid.

**Comment by netmackan** [comment]
Android 6.0.1.

**Comment by raatmarien** [comment]
That may be an issue with F-Droid, since I experience that some times with other apps on F-Droid. Try clearing the cache of F-Droid and download again, to see if that's the problem.

**Comment by licaon-kter** [comment]
Yes, retry or even download the package from the web browser.

/Close this

**Comment by netmackan** [comment]
Thank you.
Actually, it turns out that dispite the error message the app was installed and I just had to start it.
