### ISSUE TITLE
TapAndTurn running and active but no icon

### ISSUE THREAD

**Issue by zilexa** [gabm/TapAndTurn#52]
Android 9 on Pixel 1:
Although the notification says the app is running and activated, nothing happens. When I tap the notification to deactivate and tap again to activate, the notification appears as soon as I turn my screen. 
Not sure why this is happening. It will test more to see when it stops working even if the service is running and active.

Edit: it already stopped working again, less than 30sec after deactivating and activating again. The notification says it is active and running. Still no icon :( 

When I open the app, it also says the service is running and when I open the app and turn my phone the icon appears again. However within the time I needed to write the previous sentence it stopped working again :( it seems to only work for seconds. 

Could this be due to Doze?

**Comment by licaon-kter** [comment]
Did you except it in battery optimisations?

**Comment by zilexa** [comment]
I thought I had but I just learned you have to allow the app to use battery twice, screenshots attached. 

This is what I did:
1) allow the app to run in background.
Long press the app icon > App Info > Advanced > Battery.

There are two options "background restricted" and "battery optimisation". Even if you change the first one, the app will stop working.
Screenshot: https://ibb.co/mrMjaz

2. Disable battery optimisation.
 Same steps as above but now select "battery optimisation".

Select "All Apps" at the top of the screen.
Scroll to TapAndTurn, click on it.
Select "don't optimise".

Unfortunately, TapAndTurn still doesn't work after about 20-30 seconds. even though the service is running and active :(

Screenshot: https://ibb.co/d85wNe
Final result: https://ibb.co/k1ME8K

I tried rebooting my phone after disabling battery optimisation: TapAndTurn did autostart but no button appears right after it auto started. I have to deactivate and activate again. Still it only works for seconds.

**Comment by zilexa** [comment]
I unfortunately had you remove your app since I was forced to tap the notification twice every time I wanted to change the orientation. Any update on a fix? Or is this one difficult to debug?

**Comment by GrantMoyer** [comment]
I experience this too. In my case, this is the section of code that causes the bug: https://github.com/gabm/TapAndTurn/blob/f339cca9d6f6abe2c734f0bcb66ca9cc51b1a1ad/app/src/main/java/com/gabm/tapandturn/services/RotationControlService.java#L76

The physicalOrientationSensor is disabled whenever the screen turns off, but is only re-enabled when the device becomes unlocked. My phone is set up so that it only locks after 5 minutes of inactivity. When I turn the screen back on before five minutes has passed, the lock screen doesn't show, and therefore Tap'n'Turn does not reactivate. This would also probably be a problem for people who have "on-body detection" enabled.

I'll make a pull request with an ostensible fix, but unfortunately, I don't have the storage space to compile and test the changes myself.

**Comment by GrantMoyer** [comment]
Oh, also, to reproduce the issue, go to System Settings > Security > Screen Lock Settings and toggle off "Power button instantly locks" and set "Automatically Lock" to anything but "Immediately". Then, while Tap'n'Turn is active, turn the screen off, and back on before the device locks.

**Comment by zilexa** [comment]
There was a small OTA on my Pixel 1 that already had Android 9. 
Since that update, TapAndTurn is no longer necessary: a similar button appears in the navigation bar when you turn your screen! 

Exactly the same behaviour as TapAndTurn.

**Comment by licaon-kter** [comment]
Maybe reopen this?

I've build HEAD, see log comments: https://gist.github.com/licaon-kter/74921c07f1aefcea95a7d5c6346b919b

**Comment by tristan-k** [comment]
Does someone have a build available for download with the fix for android ?

**Comment by just-Nob** [comment]
V@licaon-kter    ,    c  uU xzxzzx uh-hihhuh buggy I high high .  OK OK   high I hui huh huh in in-iin y.  u u  CMG I job h   c   u
