### ISSUE TITLE
Resource optimization

### ISSUE THREAD

**Issue by AAlchemy** [gabm/TapAndTurn#6]
Works great! I just wish it used a little less RAM. Us lowly 2gb users need all the optimization we can get.

**Comment by gabm** [comment]
using less resources is always beneficial, but i honestly don't see where it is using that much RAM?

Can u provide some details:
- Android version
- RAM usage at your system

**Comment by AAlchemy** [comment]
Java is a fickle thing. It's going to make a liar out of me. Things look better this time when I looked. Just before my OP it was at least double the current usage. screenshots http://imgur.com/a/6I91F

**Comment by gabm** [comment]
hmm that somehow confirms what i can see on my phone ... I'm not sure what causes resource usage - like: when are things loaded into ram and how long are they kept... I wouldn't know how to lower the usage but as it seems ok for u, then we can close here, no?

**Comment by AAlchemy** [comment]
Yeah, this seems to be a knee-jerk false alarm. Issue can be closed. 😄
