### ISSUE TITLE
Implement Inverse Portrait and Landscape Mode

### ISSUE THREAD

**Issue by omitter** [gabm/TapAndTurn#7]
On my tablet I use inverse portrait mode most of the time.  When I hold it in inverse portrait position, the icon appears. But when I click it, screen switches to normal portrait mode, so everything is upside down. Would be great if you could implement a check for inverse portrait and inverse landscape too.

**Comment by gabm** [comment]
thanks for your bug report. That looks strange indeed... on my phone i think that the reverse portrait doesn't work but I'll reconfirm...

meanwhile you could tell me whether the icon appears properly in the other directions? it should always appear on the top right corner ...

**Comment by licaon-kter** [comment]
Can confirm issue here (Xperia 5.1.1) too... But, the device (better said Android version) does not have support for that anyway in my case, hence I'm not sure it's an app issue in the end.

My case: portrait, landscape and inverse landscape work ok, icon in upper right corner.
Inverse portrait has icon in lower left corner, or better said Android version does not report correctly that rotation.

**Comment by omitter** [comment]
For inverse portrait the icon appears on the bottom left corner. When the device is already locked in portrait mode and I turn it to inverse portrait, no icon appears at all.

Also inverse landscape is working fine. Sorry, I didn't test it properly.

**Comment by gabm** [comment]
I released a beta version that includes this feature on f-droid (requires manual update once its relased)... 

https://gitlab.com/fdroid/fdroiddata/merge_requests/1889/

Please check with this version and report back..

**Comment by licaon-kter** [comment]
Xperia 5.1.1, inverse portrait not working in 2.0beta2.

Also the icon is all over the place, either upper right or lower left, please see #16

**Comment by gabm** [comment]
@licaon-kter are you using a tablet? On phones the inverse portrait will probably not work at all.. Thats why it can be switched off.

#16 #17 is still unresolved in this beta, but also uncorrelated to this issue

**Comment by licaon-kter** [comment]
No, phone, I understand it might be a ROM limitation.

#16 helps everyone, that's why I mentioned it ;)

**Comment by gabm** [comment]
I'll release a new version soon which enables reverse portrait mode as implemented in the last beta. Please note that most phones don't support it but is intended for tablets. That's why it can be enabled/disabled by a settings switch...
