### ISSUE TITLE
Delete the persistent notification

### ISSUE THREAD

**Issue by jpggithub** [gabm/TapAndTurn#9]
Thank you very much for this app!

Can you add an option to delete the persistent notication of the app? It takes a long space in the list of notifications and it is not very useful (I think ;-) )

**Comment by licaon-kter** [comment]
Android 5 and newer can hide it, see your Settings.
It's needed (the notification is a requirement if you want the service) else Android might kill the app (service).

**Comment by gabm** [comment]
yes, its not useful but if its not there i think android kills the service/app and therefore it won't function anymore.. its like a *must-have*...

Correct me if I'm wrong though...

**Comment by gabm** [comment]
i can confirm that the workaround of @licaon-kter works very well...

i close the issue here..
